//! Tests auto-converted from "sass-spec/spec/non_conformant/extend-tests/subject-operator"

mod t200_test_extend_with_subject_transfers_subject_to_extender;

mod t201_test_extend_with_subject_transfers_subject_to_extender;

mod t202_test_extend_with_subject_retains_subject_on_target;

mod t203_test_extend_with_subject_transfers_subject_to_target;

mod t204_test_extend_with_subject_retains_subject_on_extender;

mod t205_test_extend_with_subject_fails_with_conflicting_subject;
