# Based on https://github.com/actions-rs/meta/blob/master/recipes/msrv.md

on: [push, pull_request]

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  # Run clippy on stable only
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          rustflags: ""
      - run: cargo clippy --all-features

  test-all:
    name: All Tests
    needs: [clippy, rustfmt]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.74.1
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build
      - run: cargo test -q

  test-windows:
    name: Test on Windows
    needs: [clippy, rustfmt]
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.74.1
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test -q

  test-macos:
    name: Test on MacOS
    needs: [clippy, rustfmt]
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.74.1
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test -q

  test-old:
    name: Old rust
    needs: [clippy, rustfmt]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.70.0
          - 1.68.2
          - 1.65.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: sed -i 's/"rsass-cli",/# \0/' Cargo.toml
      - run: cargo test --package rsass-macros -q
